### PR TITLE
normalize supported operating systems

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by jhoblitt** [comment]
The breakage on EL9 is probably real.

**Comment by jhoblitt** [comment]
The JDK1.8 rpms won't work on EL9, at least not with dependency resolution, because of what I suspect are changes to yum/dnf. On EL7, `/bin/mv` is resolvable:

```bash
[jhoblitt@foreman ~]$ sudo yum whatprovides /bin/mv
Loaded plugins: fastestmirror, versionlock
Loading mirror speeds from cached hostfile
 * base: www.gtlib.gatech.edu
 * epel: mirror.atl.genesisadaptive.com
 * extras: mirror.mia11.us.leaseweb.net
 * updates: ftp.usf.edu
Excluding 8 updates due to versionlock (use "yum versionlock status" to show them)
coreutils-8.22-24.el7.x86_64 : A set of basic GNU tools commonly used in shell scripts
Repo        : base
Matched from:
Filename    : /bin/mv



coreutils-8.22-24.el7_9.2.x86_64 : A set of basic GNU tools commonly used in shell scripts
Repo        : updates
Matched from:
Filename    : /bin/mv



coreutils-8.22-24.el7_9.2.x86_64 : A set of basic GNU tools commonly used in shell scripts
Repo        : @updates
Matched from:
Filename    : /bin/mv



```

but not on EL9:

```bash
[root@centos9-64 bin]# yum whatprovides /bin/mv
Last metadata expiration check: 2:43:43 ago on Mon Jan 30 17:45:27 2023.
coreutils-8.32-31.el9.x86_64 : A set of basic GNU tools commonly used in shell scripts
Repo        : baseos
Matched from:
Filename    : /usr/bin/mv

coreutils-8.32-32.el9.x86_64 : A set of basic GNU tools commonly used in shell scripts
Repo        : baseos
Matched from:
Filename    : /usr/bin/mv

coreutils-8.32-33.el9.x86_64 : A set of basic GNU tools commonly used in shell scripts
Repo        : baseos
Matched from:
Filename    : /usr/bin/mv

coreutils-8.32-34.el9.x86_64 : A set of basic GNU tools commonly used in shell scripts
Repo        : baseos
Matched from:
Filename    : /usr/bin/mv

coreutils-single-8.32-31.el9.x86_64 : coreutils multicall binary
Repo        : baseos
Matched from:
Filename    : /usr/bin/mv

coreutils-single-8.32-32.el9.x86_64 : coreutils multicall binary
Repo        : baseos
Matched from:
Filename    : /usr/bin/mv

coreutils-single-8.32-33.el9.x86_64 : coreutils multicall binary
Repo        : @System
Matched from:
Filename    : /usr/bin/mv

coreutils-single-8.32-33.el9.x86_64 : coreutils multicall binary
Repo        : baseos
Matched from:
Filename    : /usr/bin/mv

coreutils-single-8.32-34.el9.x86_64 : coreutils multicall binary
Repo        : baseos
Matched from:
Filename    : /usr/bin/mv

```

**Comment by jhoblitt** [comment]
I'm removing almalinux 9 from the metadata.json.  TL;DR - we don't want to use old jdk1.8 packages on EL9.

**Comment by jhoblitt** [comment]
@glennmorris Basically, FYI, the jdk1.8 packages are unhappy on EL9.

**Comment by glennmorris** [comment]
For context:

```
dnf localinstall./jdk-8u202-linux-x64.rpm
Error: 
 Problem: conflicting requests
  - nothing provides /bin/basename needed by jdk1.8-2000:1.8.0_202-fcs.x86_64
  etc
```

Ref [this bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1634200)

If CCS is still requiring this specific jdk version when the observatory switches to RHEL9, some solution will have to be found. Eg installing the tar version rather than the rpm version, or a compat rpm that provides the missing features.

**Review by glennmorris — APPROVED** [review]

**Pull request merged**
